Name:           ros-kinetic-raspigibbon-control
Version:        0.0.1
Release:        0%{?dist}
Summary:        ROS raspigibbon_control package

Group:          Development/Libraries
License:        MIT
URL:            http://github.com/rt-net/RaspberryPiGibbon/wiki
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-control-msgs
Requires:       ros-kinetic-controller-interface
Requires:       ros-kinetic-controller-manager
Requires:       ros-kinetic-gazebo-ros-control
Requires:       ros-kinetic-hardware-interface
Requires:       ros-kinetic-joint-state-controller
Requires:       ros-kinetic-robot-state-publisher
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-control-msgs
BuildRequires:  ros-kinetic-controller-interface
BuildRequires:  ros-kinetic-controller-manager
BuildRequires:  ros-kinetic-gazebo-ros-control
BuildRequires:  ros-kinetic-hardware-interface
BuildRequires:  ros-kinetic-joint-state-controller
BuildRequires:  ros-kinetic-robot-state-publisher
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs

%description
The raspigibbon_control package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Mar 01 2018 RT Corporation <shop@rt-net.jp> - 0.0.1-0
- Autogenerated by Bloom

